/**
 * @author Russell Toris - rctoris@wpi.edu
 */

var INTERACTIVEWORLD = INTERACTIVEWORLD || {
  REVISION : '1-devel'
};

INTERACTIVEWORLD.Z_INDEX = 0.005;

INTERACTIVEWORLD.NORTH_WALL = 0;
INTERACTIVEWORLD.EAST_WALL = 1;
INTERACTIVEWORLD.SOUTH_WALL = 2;
INTERACTIVEWORLD.WEST_WALL = 3;

INTERACTIVEWORLD.NEGATIVE_DOOR_SIDE = 0;
INTERACTIVEWORLD.POSITIVE_DOOR_SIDE = 1;

INTERACTIVEWORLD.WALL_WIDTH = 0.05;
INTERACTIVEWORLD.WALL_HEIGHT = 1.5;
INTERACTIVEWORLD.DOOR_WIDTH = 0.8;

INTERACTIVEWORLD.WORLD_WIDTH = 100;
INTERACTIVEWORLD.WORLD_HEIGHT = 100;
INTERACTIVEWORLD.WORLD_FLOOR_TEXTURE = 'grass.jpg';

INTERACTIVEWORLD.HOUSE_WIDTH = 10;
INTERACTIVEWORLD.HOUSE_HEIGHT = 8;
INTERACTIVEWORLD.HOUSE_WALL_TEXTURE = 'wall.jpg';
INTERACTIVEWORLD.HOUSE_FLOOR_TEXTURE = 'floor.jpg';

INTERACTIVEWORLD.BEDROOM_WIDTH = 4.9;
INTERACTIVEWORLD.BEDROOM_HEIGHT = 4.5;
INTERACTIVEWORLD.BEDROOM_WALL_TEXTURE = 'bedroom.jpg';
INTERACTIVEWORLD.BEDROOM_FLOOR_TEXTURE = 'carpet.jpg';

INTERACTIVEWORLD.BED_MODEL = 'bed.dae';

INTERACTIVEWORLD.DRESSER_MODEL = 'dresser.dae';